export const SET_FILTERS_VALUE = "SET_FILTERS_VALUE";
export const SET_FILTERS_OPTIONS = "SET_FILTERS_OPTIONS";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_PAGE_LENGTH = "SET_PAGE_LENGTH";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
